### ISSUE TITLE
About the "training problem"

### ISSUE THREAD

**Issue by JasonWei512** [JasonWei512/Tacotron-2-Chinese#1]
@lyz04551

> 1.Are you directly training the pinyin of the data set?
2.Have you tried training with a low sampling rate? I trained the 16khz standard dataset and the audio spectrum does not seem to be your natural.

1. Yes, I use pinyin. (For example "wan3 shang4 chi1 shen2 me5" instead of "晚上吃什么")
2. No, I only tried 48KHz (which resulted in OutOfMemory error) and 36KHz. Can you share your training corpus and predicted audio? 

另外麻烦把那个Pull Request删了吧。

**Comment by lyz04551** [comment]
> @lyz04551
> 
> > 1.Are you directly training the pinyin of the data set?
> > 2.Have you tried training with a low sampling rate? I trained the 16khz standard dataset and the audio spectrum does not seem to be your natural.
> 
> 1. Yes, I use pinyin. (For example "wan3 shang4 chi1 shen2 me5" instead of "晚上吃什么")
> 2. No, I only tried 48KHz (which resulted in OutOfMemory error) and 36KHz. Can you share your training corpus and predicted audio?
> 
> 另外麻烦把那个Pull Request删了吧。

最近使用wavernn出的声音还可以，你有使用过类似声码器么

**Comment by JasonWei512** [comment]
没有，只是玩玩

**Comment by lyz04551** [comment]
> 没有，只是玩玩

好的，有问题随时交流

**Comment by JasonWei512** [comment]
[WaveNet.zip](https://github.com/JasonWei512/Tacotron-2-Chinese/files/3567668/WaveNet.zip)
248K步 很多噪音
input_type:raw  out_channels:2

**Comment by xinzheshen** [comment]
@JasonWei512 您好，请教个问题。我用您的预训练的模型合成语音时，音色不错，但有时候断句有问题，如“刚毅 豪迈 执着”， 会读成“刚毅豪 迈执着”，您知道可能是什么原因或有什么办法规避这个问题吗？十分感谢。

**Comment by JasonWei512** [comment]
@xinzheshen 
没什么好办法，训练语料的文本没标点
要么多生成几次选一个读的对的（因为dropout每次生成的语音都有点不同），要么把文本断成三句再手动拼接语音：
gang1 yi4 hao2 mai4 zhi2 zhuo2
↓
gang1 yi4 
hao2 mai4 
zhi2 zhuo2

**Comment by xinzheshen** [comment]
@JasonWei512 多谢，我也在考虑长句拆短句，但就是需要想想按什么原则去拆。另外您有没有训练过带标点的语料集呢?

**Comment by JasonWei512** [comment]
@xinzheshen 没有试过，我只找到标贝这么一个现成的高质量开源中文语音合成语料库

**Comment by JasonWei512** [comment]
@lyz04551 
我在试 WaveNet，传了一些样本：https://github.com/JasonWei512/Tacotron-2-Chinese/issues/4
