### ISSUE TITLE
咨询一下这个中文的预训练模型需要中英文都说的话能支持么

### ISSUE THREAD

**Issue by zhilangtaosha** [JasonWei512/Tacotron-2-Chinese#13]
我看一些生成的案例都是全中文环境 ，数字和英文之类的效果怎么样 ？

**Comment by JasonWei512** [comment]
数字打拼音可以，英文不行

**Comment by zhilangtaosha** [comment]
> 数字打拼音可以，英文不行

我想弄一套自己的TTS，我看之前有人提过问题了，我尝试了一下风格迁移的技术，效果都不太好，您有推荐的风格迁移的实现没，就是有训练好的模型的，我没啥计算资源
