### ISSUE TITLE
请问一下你训练完的模型在GTA=False下效果如何

### ISSUE THREAD

**Issue by LZ-QWQ** [JasonWei512/Tacotron-2-Chinese#3]
我看到原作者 rayhane-mamah下有的issues说GTA关了以后效果就不是很好，我自己的暂未完成，想请问你的效果怎么样，，，我也是用的标贝语音

**Comment by JasonWei512** [comment]
你是指用非GTA训练Wavenet的效果吗？没有试过

**Comment by LZ-QWQ** [comment]
> 你是指用非GTA训练Wavenet的效果吗？没有试过

啊不不不，用非GTA模式生成梅尔频谱，就是比如  我给一段中文（不在标贝数据集里）  然后模型直接生成的梅尔频谱效果怎么样  比如把他丢到GL生成音频这样  [像这个提到的](https://github.com/Rayhane-mamah/Tacotron-2/issues/299)

**Comment by JasonWei512** [comment]
> 你是指用非GTA训练Wavenet的效果吗？没有试过
> 
> 啊不不不，用非GTA模式生成梅尔频谱，就是比如  我给一段中文（不在标贝数据集里）  然后模型直接生成的梅尔频谱效果怎么样  比如把他丢到GL生成音频这样  像这个提到的

非GTA用GL生成的效果：[Griffin-Lim.zip](https://github.com/JasonWei512/Tacotron-2-Chinese/files/3990895/Griffin-Lim.zip)

**Comment by LZ-QWQ** [comment]
> > 你是指用非GTA训练Wavenet的效果吗？没有试过
> > 啊不不不，用非GTA模式生成梅尔频谱，就是比如  我给一段中文（不在标贝数据集里）  然后模型直接生成的梅尔频谱效果怎么样  比如把他丢到GL生成音频这样  像这个提到的
> 
> 非GTA用GL生成的效果：[Griffin-Lim.zip](https://github.com/JasonWei512/Tacotron-2-Chinese/files/3990895/Griffin-Lim.zip)

哇，谢谢，感觉效果挺好的~麻烦你了

**Comment by vcen** [comment]
@JasonWei512 怎么联系您，合作。

**Comment by neoragex2002** [comment]
我自己训练也发现了，这个不在标贝数据集里的文字+非GTA+GL合成语音有明显颤音，不知是啥原因，能有办法改善吗? @JasonWei512
